### ISSUE TITLE
Bulk import support

### ISSUE THREAD

**Issue by nozaq** [treasure-data/td-client-node#1]
Any plan to support the bulk import function as [td-client-ruby](https://github.com/treasure-data/td-client-ruby)?

**Comment by Lewuathe** [comment]
Sorry I forgot to mention here explicitly. Bulk Import API is [now supported from v0.2.5](https://github.com/treasure-data/td-client-node/pull/15). 
Please let us know if there is something wrong. I'll close this issue. Thanks.
